### ISSUE TITLE
Make it possible to switch locales in a running sim

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1302]
As @arouinfar mentioned in https://github.com/phetsims/joist/issues/744#issuecomment-1197440891, we would like the simulation to be able to switch languages from within the sim.

> Eventually the Localization Settings will include a UI control for users to select the sim locale within the all file.

And in https://github.com/phetsims/studio/issues/192#issuecomment-730570376, where @kathy-phet also said:

> KP: Yes, changing language dynamically is highly desirable if we can accomplish it.

This came up during https://github.com/phetsims/studio/issues/268 where @zepumph and I discovered that the locale query parameter wouldn't work out of the box because the text strings are phetioState: true and hence get overwritten by the state object.  Uninstrumenting from state would make them non-customizable.

So I wanted to explore a path for changing the locale from within the sim, now that we have a vision for dynamic layout in https://github.com/phetsims/joist/issues/608

I found that including all languages into the Gravity and Orbits all HTML file only increased the size from 2.8MB to 3.9MB or so, and I am not too worried about that additional size.  I used this build command, but had to output a non-debug _all version by a change in chipper:

```
grunt --brands=phet --locales=* --allHTML --lint=false
```

I experimented with an idea that getStringModule loads strings (for compatibility with existing code), but also loads a corresponding stringProperty (using a copy/paste preloadable TinyProperty).  This means existing code will continue to work, but we can opt-in to a changeable string on a case-by-case basis.  I tested this out with Gravity and Orbits, and was able to get several strings switching dynamically at runtime in both built and unbuilt mode.

https://user-images.githubusercontent.com/679486/184061833-5a379fec-73b1-4786-b0dd-28ff9629fa87.mov

Here's the working copy experiment, which also changes the sim title.

<details>

```diff

Index: main/chipper/js/load-unbuilt-strings.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/main/chipper/js/load-unbuilt-strings.js b/main/chipper/js/load-unbuilt-strings.js
--- a/main/chipper/js/load-unbuilt-strings.js	(revision a63678534e0fa11d5154b3ffa8f8aa96e0e5fd09)
+++ b/main/chipper/js/load-unbuilt-strings.js	(date 1660188114399)
@@ -114,6 +114,8 @@
   const loadCustomLocale = customLocale && customLocale !== FALLBACK_LOCALE;
   const locales = [
     FALLBACK_LOCALE,
+    'es',
+    'ar',
     ...( loadCustomLocale ? [ customLocale ] : [] ), // e.g. 'zh_CN'
     ...( ( loadCustomLocale && customLocale.length > 2 && customLocale.slice( 0, 2 ) !== FALLBACK_LOCALE ) ? [ customLocale.slice( 0, 2 ) ] : [] ) // e.g. 'zh'
   ];
Index: main/chipper/js/grunt/getStringMap.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/main/chipper/js/grunt/getStringMap.js b/main/chipper/js/grunt/getStringMap.js
--- a/main/chipper/js/grunt/getStringMap.js	(revision a63678534e0fa11d5154b3ffa8f8aa96e0e5fd09)
+++ b/main/chipper/js/grunt/getStringMap.js	(date 1660187830557)
@@ -215,9 +215,10 @@
             }
           }
         }
-        assert( stringValue !== null, `Missing string information for ${repo} ${partialStringKey}` );
-
-        stringMap[ locale ][ `${requirejsNamespaceMap[ repo ]}/${partialStringKey}` ] = stringValue;
+        if ( !partialStringKey.endsWith( 'Property' ) ) {
+          assert( stringValue !== null, `Missing string information for ${repo} ${partialStringKey}` );
+          stringMap[ locale ][ `${requirejsNamespaceMap[ repo ]}/${partialStringKey}` ] = stringValue;
+        }
       } );
     } );
   } );
Index: main/joist/js/Sim.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/main/joist/js/Sim.ts b/main/joist/js/Sim.ts
--- a/main/joist/js/Sim.ts	(revision 2d4bd8098beba3cb65613a546147662aff0da2af)
+++ b/main/joist/js/Sim.ts	(date 1660187744230)
@@ -261,7 +261,10 @@
    * @param allSimScreens - the possible screens for the sim in order of declaration (does not include the home screen)
    * @param [providedOptions] - see below for options
    */
-  public constructor( name: string, allSimScreens: Screen[], providedOptions?: SimOptions ) {
+  public constructor( nameProperty: string, allSimScreens: Screen[], providedOptions?: SimOptions ) {
+
+    // @ts-ignore
+    const name = nameProperty.value;
 
     window.phetSplashScreenDownloadComplete();
 
@@ -319,6 +322,10 @@
                            'and the title text on the home screen, if it exists.'
     } );
 
+
+    // @ts-ignore
+    nameProperty.link( name => { this.simNameProperty.value = name; } );
+
     // playbackModeEnabledProperty cannot be changed after Sim construction has begun, hence this listener is added before
     // anything else is done, see https://github.com/phetsims/phet-io/issues/1146
     phet.joist.playbackModeEnabledProperty.lazyLink( () => {
Index: main/gravity-and-orbits/js/gravity-and-orbits-main.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/main/gravity-and-orbits/js/gravity-and-orbits-main.ts b/main/gravity-and-orbits/js/gravity-and-orbits-main.ts
--- a/main/gravity-and-orbits/js/gravity-and-orbits-main.ts	(revision 33960849867f0ae2b9561565231dd1e825993a38)
+++ b/main/gravity-and-orbits/js/gravity-and-orbits-main.ts	(date 1660187885995)
@@ -18,7 +18,10 @@
 import ToScaleScreen from './toScale/ToScaleScreen.js';
 
 // @ts-ignore
-const gravityAndOrbitsTitleString = gravityAndOrbitsStrings[ 'gravity-and-orbits' ].title;
+gravityAndOrbitsStrings[ 'gravity-and-orbits' ].title;
+
+// @ts-ignore
+const gravityAndOrbitsTitleStringProperty = gravityAndOrbitsStrings[ 'gravity-and-orbits' ].titleProperty;
 
 simLauncher.launch( () => {
 
@@ -53,5 +56,5 @@
     backgroundColorProperty: backgroundColorProperty,
     tandem: Tandem.ROOT.createTandem( 'toScaleScreen' )
   } );
-  new Sim( gravityAndOrbitsTitleString, [ modelScreen, toScaleScreen ], simOptions ).start();
+  new Sim( gravityAndOrbitsTitleStringProperty, [ modelScreen, toScaleScreen ], simOptions ).start();
 } );
\ No newline at end of file
Index: main/gravity-and-orbits/js/common/view/GravityControl.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/main/gravity-and-orbits/js/common/view/GravityControl.ts b/main/gravity-and-orbits/js/common/view/GravityControl.ts
--- a/main/gravity-and-orbits/js/common/view/GravityControl.ts	(revision 33960849867f0ae2b9561565231dd1e825993a38)
+++ b/main/gravity-and-orbits/js/common/view/GravityControl.ts	(date 1660188512301)
@@ -43,8 +43,8 @@
     }, providedOptions );
 
     const gravityTextNode = new Text( gravityString, TEXT_OPTIONS );
-    const onTextNode = new Text( onString, TEXT_OPTIONS );
-    const offTextNode = new Text( offString, TEXT_OPTIONS );
+    const onTextNode = new Text( onString, { ...TEXT_OPTIONS, textProperty: gravityAndOrbitsStrings.onProperty } );
+    const offTextNode = new Text( offString, { ...TEXT_OPTIONS, textProperty: gravityAndOrbitsStrings.offProperty } );
 
     this.addLinkedElement( gravityEnabledProperty, {
       tandem: options.tandem.createTandem( 'gravityEnabledProperty' )
@@ -60,5 +60,10 @@
   }
 }
 
-gravityAndOrbits.register( 'GravityControl', GravityControl );
+gravityAndOrbits
+  .register(
+    'GravityControl'
+    ,
+    GravityControl
+  );
 export default GravityControl;
\ No newline at end of file
Index: main/scenery-phet/js/TimeSpeedRadioButtonGroup.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/main/scenery-phet/js/TimeSpeedRadioButtonGroup.ts b/main/scenery-phet/js/TimeSpeedRadioButtonGroup.ts
--- a/main/scenery-phet/js/TimeSpeedRadioButtonGroup.ts	(revision c4e25406c328bdd0eba2df0e2abdf7b7e5018950)
+++ b/main/scenery-phet/js/TimeSpeedRadioButtonGroup.ts	(date 1660188365027)
@@ -22,9 +22,9 @@
 
 // maps TimeSpeed to its label and Tandem name
 const SPEED_LABEL_MAP = new Map();
-SPEED_LABEL_MAP.set( TimeSpeed.FAST, { labelString: sceneryPhetStrings.speed.fast, tandemName: 'fastRadioButton' } );
-SPEED_LABEL_MAP.set( TimeSpeed.NORMAL, { labelString: sceneryPhetStrings.speed.normal, tandemName: 'normalRadioButton' } );
-SPEED_LABEL_MAP.set( TimeSpeed.SLOW, { labelString: sceneryPhetStrings.speed.slow, tandemName: 'slowRadioButton' } );
+SPEED_LABEL_MAP.set( TimeSpeed.FAST, { textProperty: sceneryPhetStrings.speed.fastProperty, labelString: sceneryPhetStrings.speed.fast, tandemName: 'fastRadioButton' } );
+SPEED_LABEL_MAP.set( TimeSpeed.NORMAL, { textProperty: sceneryPhetStrings.speed.normalProperty, labelString: sceneryPhetStrings.speed.normal, tandemName: 'normalRadioButton' } );
+SPEED_LABEL_MAP.set( TimeSpeed.SLOW, { textProperty: sceneryPhetStrings.speed.slowProperty, labelString: sceneryPhetStrings.speed.slow, tandemName: 'slowRadioButton' } );
 
 type SelfOptions = {
   radius?: number;
@@ -69,8 +69,13 @@
 
     const items = timeSpeeds.map( speed => {
 
+      SPEED_LABEL_MAP.get( speed ).textProperty.link( speed );
+
       const speedLabel = SPEED_LABEL_MAP.get( speed ).labelString;
-      const labelNode = new Text( speedLabel, options.labelOptions );
+      const labelNode = new Text( speedLabel, {
+        ...options.labelOptions,
+        textProperty: SPEED_LABEL_MAP.get( speed ).textProperty;
+      } );
 
       return {
         value: speed,
Index: main/chipper/js/getStringModule.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/main/chipper/js/getStringModule.js b/main/chipper/js/getStringModule.js
--- a/main/chipper/js/getStringModule.js	(revision a63678534e0fa11d5154b3ffa8f8aa96e0e5fd09)
+++ b/main/chipper/js/getStringModule.js	(date 1660188479012)
@@ -16,7 +16,7 @@
 
 /**
  * @param {string} requirejsNamespace - E.g. 'JOIST', to pull string keys out from that namespace
- * @returns {Object} - Nested object to be accessed like joistStrings.ResetAllButton.name
+ * @returns {Object} - Nested object to be accessed like joistStrings.ResetAllButton.name.value
  */
 const getStringModule = requirejsNamespace => {
   // Our string information is pulled globally, e.g. phet.chipper.strings[ locale ][ stringKey ] = stringValue;
@@ -98,7 +98,51 @@
         // In case our assertions are not enabled, we'll need to proceed without failing out (so we allow for the
         // extended string keys in our actual code, even though assertions should prevent that).
         if ( typeof reference !== 'string' ) {
-          reference[ lastKeyPart ] = phet.chipper.mapString( partialStringMap[ stringKey ] );
+
+          class TinyProperty {
+
+            constructor( value ) {
+              this.value = value;
+              this.listeners = [];
+            }
+
+            link( listener ) {
+              this.listeners.push( listener );
+              listener( this.value );
+            }
+
+            isSettable(){
+              return true;
+            }
+
+            set(value){
+              this.value = value;
+            }
+
+            lazyLink( listener ) {
+              this.listeners.push( listener );
+            }
+          }
+
+          const tp = new TinyProperty( phet.chipper.mapString( partialStringMap[ stringKey ] ) );
+          reference[ lastKeyPart ] = tp.value;
+          reference[ lastKeyPart + 'Property' ] = tp;
+
+          const locales = [ 'en', 'es', 'ar' ];
+
+          let localeIndex = 0;
+
+          setInterval( () => {
+
+            localeIndex++;
+            const locale = locales[ localeIndex % locales.length ];
+            //
+            const partialStringMap = phet.chipper.strings[ locale ];
+            const value = phet.chipper.mapString( partialStringMap[ stringKey ] ) || '?';
+
+            tp.value = value;
+            tp.listeners.forEach( listener => listener( tp.value ) );
+          }, 1000 );
         }
       } );
 
Index: main/gravity-and-orbits/js/common/view/CheckboxPanel.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/main/gravity-and-orbits/js/common/view/CheckboxPanel.ts b/main/gravity-and-orbits/js/common/view/CheckboxPanel.ts
--- a/main/gravity-and-orbits/js/common/view/CheckboxPanel.ts	(revision 33960849867f0ae2b9561565231dd1e825993a38)
+++ b/main/gravity-and-orbits/js/common/view/CheckboxPanel.ts	(date 1660188660811)
@@ -71,12 +71,12 @@
     const children = [];
     const options = combineOptions<CheckboxPanelOptions>( { tandem: Tandem.OPTIONAL }, providedOptions );
 
-    const gravityForceTextNode = new Text( gravityForceString, TEXT_OPTIONS );
-    const velocityTextNode = new Text( velocityString, TEXT_OPTIONS );
-    const massTextNode = new Text( massString, TEXT_OPTIONS );
-    const pathTextNode = new Text( pathString, TEXT_OPTIONS );
-    const gridTextNode = new Text( gridString, TEXT_OPTIONS );
-    const measuringTapeTextNode = new Text( measuringTapeString, TEXT_OPTIONS );
+    const gravityForceTextNode = new Text( gravityForceString, { ...TEXT_OPTIONS, textProperty: gravityAndOrbitsStrings.gravityForceProperty } );
+    const velocityTextNode = new Text( velocityString, { ...TEXT_OPTIONS, textProperty: gravityAndOrbitsStrings.velocityProperty } );
+    const massTextNode = new Text( massString, { ...TEXT_OPTIONS, textProperty: gravityAndOrbitsStrings.massProperty } );
+    const pathTextNode = new Text( pathString, { ...TEXT_OPTIONS, textProperty: gravityAndOrbitsStrings.pathProperty } );
+    const gridTextNode = new Text( gridString, { ...TEXT_OPTIONS, textProperty: gravityAndOrbitsStrings.gridProperty } );
+    const measuringTapeTextNode = new Text( measuringTapeString, { ...TEXT_OPTIONS, textProperty: gravityAndOrbitsStrings.measuringTapeProperty } );
     const optionsWithTandem = ( tandemName: string ) => merge( { tandem: options.tandem!.createTandem( tandemName ) }, CHECKBOX_OPTIONS );
 
     // gravity force checkbox

```

</details>

Note there are several lint issues, type issues, etc in this experiment--just wanted to explore if this is where we want to be.  Also, I created this issue here in chipper since that is where the strings are loaded and processed, even though this could have a Joist UI and overlap with a11y preferences and phet-io customizability.

Also heads up to @zepumph and @jessegreenberg and @pixelzoom about this idea.

UPDATE: Also heads up to @jbphet and @liam-mulhall since they work on rosetta.

**Comment by jonathanolson** [comment]
Not done, but committed some progress (Molecule Shapes sim-specific is completely dynamic now, a lot of Gravity and Orbits is, but need to work on some details and some common interface).

phetioValidation=false is needed for now, due to overrides file errors like:
```
moleculeShapes.general.view.navigationBar.phetButton.phetMenu.optionsDialogCapsule.archetype.content.showOuterLonePairsCheckbox.labelText.textProperty:  3. Any schema entries in the overrides file must exist in the baseline file.
```

Example is http://localhost/studio/?sim=molecule-shapes&phetioWrapperDebug=true&phetioElementsDisplay=all&loadExtraLocales=es,ar_SA,de,cs&phetioValidation=false

I added the loadExtraLocales query parameter (for unbuilt sims, since they by default only load the NEEDED locales).

`SIM.general.view.localeProperty` controls the locale. Strings are in the studio interface, but it lags the studio interface a bit (even with only that many locales).

**Comment by jonathanolson** [comment]
Added a VERY rough-draft locale switcher in the navbar for demo-ing, see https://bayes.colorado.edu/dev/olsonjb/locale-test.html

**Comment by samreid** [comment]
That draft looks really amazing, nice work!

**Comment by jonathanolson** [comment]
Includes some layout/helper improvements that I'll port to master in the commits above.

**Comment by jonathanolson** [comment]
Gravity and Orbits sim-specific stuff complete, demo: https://bayes.colorado.edu/dev/olsonjb/locale-test2.html

PhetMenu and related things is what's remaining (PhetMenu needs... a layout rework). Most of the code is pretty good quality. Some annoyances that we don't have a "derived-style" Property we can pass to `textProperty` (it needs an `IProperty`), so I had to create some things that behaved like DerivedProperty (we'd need a good solution). Additionally, ButtonNode needs some layout work so that it resizes down (wrapped 1 button in a VBox as a workaround).

The largest bulk of things is just converting things to text Properties, not the actual layout work.

**Comment by samreid** [comment]
I checked out the branches, launched Gravity and Orbits in studio with `?loadExtraLocales=en,es,ja,ar` and `&phetioDebug=false` and was able to use studio to customize the text in English and Spanish.  Then after pressing "Test", I was able to see both translated strings in the loaded sim. This is working really well.  The lag in showing so many elements under strings.en wasn't very severe for me, but some ideas for streamlining that UX: add nesting substructure to the tree, like string.en.JOIST.a11y etc.  Or showing all strings in more of a custom table format like rosetta.  (we could ultimately do both)

**Comment by jonathanolson** [comment]
Made the PhetMenu fully dynamic above (we'll probably want that dynamic layout and code simplification, even if we're not keeping other code)

**Comment by jonathanolson** [comment]
> add nesting substructure to the tree, like string.en.JOIST.a11y etc. Or showing all strings in more of a custom table format like rosetta. (we could ultimately do both)

Yes, I wasn't sure what to do. Tandems have a very restricted set of characters, and string keys don't, so coming up with a good mapping (or... better studio interface?) would be needed.

**Comment by jonathanolson** [comment]
Our string detection system doesn't like `joistStrings.projectorModeProperty.link( ... )`, it treats the `link` as included in the string name.

**Comment by jonathanolson** [comment]
I tossed the about/preferences/update dialogs into dynamic layout + dynamic strings above. This should cover all visible strings in GAO/MS demos.

Demos:
Gravity and Orbits: https://bayes.colorado.edu/dev/olsonjb/locale-test3.html
Molecule Shapes: https://bayes.colorado.edu/dev/olsonjb/locale-test4.html

**Comment by zepumph** [comment]
@samreid and I worked on improving the look of the phetioIDs by using camelCase and splitting on `-` instead of `,`. There was one problem I ran into when we moved to commit: In SOM there is a string key called `Solid` and `solid`, so the camelCasing of those two overlap and cause an error. 

https://github.com/phetsims/states-of-matter/blob/274528b93182eda8923cbed369925896c8ea4e31/states-of-matter-strings_en.json#L11-L22

Here is what we want to commit:

<details>

```diff

Index: js/getStringModule.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/getStringModule.js b/js/getStringModule.js
--- a/js/getStringModule.js	(revision d4e7f411912bfe08f6d52663439177c24e68f66d)
+++ b/js/getStringModule.js	(date 1660674967548)
@@ -190,19 +190,24 @@
     // In case our assertions are not enabled, we'll need to proceed without failing out (so we allow for the
     // extended string keys in our actual code, even though assertions should prevent that).
     if ( typeof reference !== 'string' ) {
-      // TODO: Improve tandem names, see https://github.com/phetsims/chipper/issues/1302
-      const sanitizedStringKey = stringKey
-        .replace( /_/g, ',' )
-        .replace( /\./g, ',' )
-        .replace( /-/g, ',' )
-        .replace( /\//g, ',' );
+      let tandem = Tandem.GENERAL_MODEL.createTandem( 'strings' ).createTandem( _.camelCase( requirejsNamespace ) );
+      for ( let i = 0; i < keyParts.length; i++ ) {
+
+        // TODO: a11y comes out as a11Y which is awkward, https://github.com/phetsims/chipper/issues/1302
+        let tandemName = _.camelCase( keyParts[ i ] );
+        if ( i === keyParts.length - 1 ) {
+          tandemName += 'StringProperty'; // append to the last element of the phetioID
+        }
+        tandem = tandem.createTandem( tandemName );
+      }
+
       const dynamicProperty = new DynamicProperty( localeProperty, {
         derive: locale => localePropertiesMap[ locale ][ stringKey ],
         bidirectional: true,
         phetioReadOnly: false,
         phetioValueType: StringIO,
         phetioState: false,
-        tandem: Tandem.GENERAL_MODEL.createTandem( 'strings' ).createTandem( `${sanitizedStringKey}Property` )
+        tandem: tandem
       } );
 
       reference[ `${lastKeyPart}Property` ] = dynamicProperty;

**Comment by samreid** [comment]
@zepumph and I considered that we can bump and index in cases like this, so it would be solid2StringProperty.

**Comment by zepumph** [comment]
Assigning @samreid to work on that!

**Comment by zepumph** [comment]
Still to do from PhET-iO meeting today:

- [ ] Overrides files deleted textProperty featured. Likely they should be changed to featuring the model
- [ ] Apply the above patch about renaming the tandem structure in https://github.com/phetsims/chipper/issues/1302#issuecomment-1217010895
- [ ] Do we NEED to add jsondiffpatch to our sim code?
- [ ] Customizing translated strings that aren't rosetta i18n. (in https://github.com/phetsims/chipper/issues/1307)
- [ ] Linking back to model-side string Properties when using pattern fillin. Perhaps through derivedProperty dependencies in https://github.com/phetsims/axon/issues/408

**Comment by zepumph** [comment]
We discussed more in PhET-iO meeting, and also discussed further with @samreid and @jonathanolson for a bit after. @jonathanolson and I decided on the following steps after a lengthy discussion. This implementation (to prototype before next design meeting for feedback), covers all design concerns we heard today while being general, modular, and simple enough to warrant an initial pass before checking in with designers. The main piece we wanted to make sure we covered is the UX for setting locales, and the behavior of other locales when setting a locale. The main change in implementation that no one else has seen yet is a fallbackLocalesProperty, in which you have Properties pointing to their fallbacks instead of actually copying their initial values. From here you can then know if you yourself have been customized, or if you are just using a fallback. 


"Locale fallback for i18n"

* Behavior:
  * en: vectors
  * de: Wektors
  * ar (not provided): vectors
  * Don't hard code, but make a pointer from ar -> en so en customization changes ar too.
  * In PhET-iO if en changes vectors to "arrows", ar is "arrows" too
  * In PhET-iO if ar and change string to "super arrows". What happens:
	* "unhook"/"override" the linkage from ar back to en, separating the two because ar has now been "translated"
	* NEVER WANT: en to change to "super arrows"
  * In PHET-iO if en changes to "more arrows", this DOESN"T change ar from "super arrows"
  * ar can NEVER be "arrows" at this point.
  * At this time, ar cannot go back to pointing to en, because a translation has been provided in PhET-iO. But! In the future we could potentially have a way to "release" a translation, and make a locale take on its fallback value instead (like to guard against mistakenly translating something in Studio).
* Implementation:
  - [ ] Add `null` as a valid value to all TinyProperties. The DynamicProperty aspect, if seeing a `null`, will go to through the "fallback" algorithm to get the current value. 
  - [ ] Add an instrumented "fallbackLocalesProperty", an ordered list (which will always have en as part of it). 
  	 * When this changes, we just switch out target according to this array.
  	 * [ en, es, de ] means you fallback to en first, and if there is no translation there you try es, and then de last. So to see de you would need to not have a value for locales X, en, and es.
  - [ ] Factoring out getStringModule code to be used by Localization property.	 
  - [ ] There will only be a single strings state for PhET-iO, in which you register individual, instrumented strings to it, and the stringsState will handle it.
  - [ ] String state Property will likely want to use `CouldNotYetDeserializeError` to mark when it doesn't have all the dynamic Properties it is storing state for available to it in the sim just yet. Throwing this error will trigger the state engine to give up for this round, try setting other items, and then come back to stringState on next iteration. There are other ways to form this state setting dependency order if this doesn't seem good or obvious.

@jonathanolson will take a first pass. Thanks!

**Comment by zepumph** [comment]
Above completes https://github.com/phetsims/chipper/issues/1302#issuecomment-1217010895. @jonathanolson please review and feel free to simplify.

**Comment by jonathanolson** [comment]
I believe the work above has mainly been completed, but I'd like to pair with a more experienced phet-io developer to get the "dynamically created strings" to work nicely.

> Add null as a valid value to all TinyProperties. The DynamicProperty aspect, if seeing a null, will go to through the "fallback" algorithm to get the current value.

Did not do this. TinyOverrideProperty has an `isOverridden`, and the chains of overridden Properties end up being much cleaner.

> Add an instrumented "fallbackLocalesProperty", an ordered list (which will always have en as part of it).

Added (so now other languages can be used in the fallback order).

> String state Property will likely want to use CouldNotYetDeserializeError

This was not needed, unless I'm completely misunderstanding. Is there a possibility that string modules won't be loaded before phet-io state will be set? If all string modules have loaded (i.e. we've created module resolution for sure), then it's ready for state to be set.

Additionally, state is restructured for the string key setup.

**Comment by zepumph** [comment]
>This was not needed, unless I'm completely misunderstanding. Is there a possibility that string modules won't be loaded before phet-io state will be set? If all string modules have loaded (i.e. we've created module resolution for sure), then it's ready for state to be set.

This won't be needed until you add state from a dynamically created string. Because at that point it is just arbitrary state key ordering that determines if the stringsStateProperty is set first, or if the (for example) circuit vertex is created first (then creating its label string Property). There won't be a case for this until https://github.com/phetsims/chipper/issues/1307.

**Comment by samreid** [comment]
I tried using LocalizedString in Vertex.ts like so:

```diff
Index: js/model/Vertex.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/model/Vertex.ts b/js/model/Vertex.ts
--- a/js/model/Vertex.ts	(revision 37d1218b8af8893b7c084ebe132081e9c3dc6b00)
+++ b/js/model/Vertex.ts	(date 1660944689331)
@@ -11,7 +11,6 @@
 import TEmitter from '../../../axon/js/TEmitter.js';
 import NumberProperty from '../../../axon/js/NumberProperty.js';
 import Property from '../../../axon/js/Property.js';
-import StringProperty from '../../../axon/js/StringProperty.js';
 import Vector2 from '../../../dot/js/Vector2.js';
 import Vector2Property from '../../../dot/js/Vector2Property.js';
 import optionize from '../../../phet-core/js/optionize.js';
@@ -19,6 +18,8 @@
 import Tandem from '../../../tandem/js/Tandem.js';
 import IOType from '../../../tandem/js/types/IOType.js';
 import circuitConstructionKitCommon from '../circuitConstructionKitCommon.js';
+import LocalizedString from '../../../chipper/js/LocalizedString.js';
+import TReadOnlyProperty from '../../../axon/js/TReadOnlyProperty.js';
 
 // Index counter for debugging
 let counter = 0;
@@ -82,7 +83,7 @@
   // for black box study
   public outerWireStub: boolean;
   public isCuttableProperty: BooleanProperty;
-  public labelTextProperty: StringProperty;
+  public labelTextProperty: TReadOnlyProperty<string>;
 
   public static VertexIO: IOType;
 
@@ -147,9 +148,12 @@
       tandem: options.tandem.createTandem( 'isCuttableProperty' )
     } );
 
-    this.labelTextProperty = new StringProperty( '', {
-      tandem: options.tandem.createTandem( 'labelTextProperty' )
-    } );
+    // this.labelTextProperty = new StringProperty( '', {
+    //   tandem: options.tandem.createTandem( 'labelTextProperty' )
+    // } );
+
+    const localizedString = new LocalizedString( '', options.tandem.createTandem( 'labelText' ).phetioID, options.tandem.createTandem( 'labelTextProperty' ) );
+    this.labelTextProperty = localizedString.property;
   }
 
   /**
```

Then:
* launch studio
* drag out a resistor
* navigate to the leftmost vertex node (via autoselect)
* navigate to the corresponding vertex model element
* set the text. ====> observe that it updates in all languages, nice!
* change locale to swedish
* set the text to something else
* switch back and forth between english and swedish, and see that the languages update correctly 

Up until now, everything is working great! But:
* Press "test"
* See that all strings have the default
* Change locales ====> strings do not update

It could be that I'm not using LocalizedString properly, or perhaps it does not yet support state like we want.

**Comment by samreid** [comment]
I believe @zepumph understood this error case when he described how we would solve it with CouldNotYetDeserializeError.  I have a working prototype that seems to be working well.

**Comment by samreid** [comment]
I committed that improvement, and testing customized multi-language strings on dynamic Vertex elements seems to be working well.  Some ideas for next steps:

- [ ] Should `LocalizedString` register itself with `getStringModule.localizedStrings`? And unregister on dispose?
- [ ] getStringModule may benefit from TypeScript

**Comment by samreid** [comment]
I restored support for stringTest query parameter, @jonathanolson I added mapString in 2 places but not sure if it was needed in:

```ts
      // Change our stringModule based on the Property value
      localizedString.property.link( string => {
        reference[ lastKeyPart ] = string;
      } );
```

Please review.

**Comment by jonathanolson** [comment]
The change above to fix stringTest looks good.

**Comment by samreid** [comment]
@zepumph pointed out that studio can be used to cycle through all the locales for testing.  Great!

**Comment by samreid** [comment]
All known work complete or moved to side issues.  @zepumph will review the implementation.  Thanks!

**Comment by zepumph** [comment]
Review:

* It looks like all commits from stringProperties branches have been merged to master. Can we please delete the branches and close the issues?
* Here is the list of new Properties related to i18n. Should we move these under an i18n folder? `joist/js/i18n/*`?

  	        fallbackLocalesProperty
  	        isLeftOrRightProperty
  	        localeOrderProperty
  	        localeProperty

* Please add documentation to the `usedLocales` function as to whether the order matters.
* `onLocaleOrderChange` has this documentation: "Do this in reverse order to AVOID infinite loops . . .". It isn't clear to me if this is meant to explain the order of spreading into the `locales` variable, or the order of the for loop. Please be a bit clearer, or just add another line of doc for the for loop.
* There is a bug or at least weirdness in this code in localeOrderProperty. Given localeProperty: de and fallbackLocalesProperty set to [ar_MA, es], the localeOrder becomes ['de', 'ar_MA', 'es', 'ar', 'en']. Should we order the aribic locales together?

  ```js
  // Attempt to fill in language reductions if they are not explicitly included, e.g. 'zh_CN' => 'zh'
  localeOrder.forEach( locale => {
    const shortLocale = locale.slice( 0, 2 );
    if ( locale !== shortLocale && !localeOrder.includes( shortLocale ) ) {
      localeOrder.push( shortLocale );
    }
  } );
  ```
* window.phet.chipper.mapString now seems to take a `TReadOnlyProperty | string`, can we update the documentation.


I see no more TODOs pointing to this issue. Thanks for all the hard work. Things are looking really fine!

**Comment by jonathanolson** [comment]
> It looks like all commits from stringProperties branches have been merged to master. Can we please delete the branches and close the issues?

Branches deleted.

**Comment by jonathanolson** [comment]
> window.phet.chipper.mapString now seems to take a TReadOnlyProperty | string, can we update the documentation.

Looking at the implementation and usages, I don't see how that's true, thoughts?

**Comment by jonathanolson** [comment]
> There is a bug or at least weirdness in this code in localeOrderProperty. Given localeProperty: de and fallbackLocalesProperty set to [ar_MA, es], the localeOrder becomes ['de', 'ar_MA', 'es', 'ar', 'en']. Should we order the aribic locales together?

I have a preference for all the exact locales first, then fallbacks (since `ar` could have translations that might not be understood by someone who knwos `ar_MA` and `es`)

**Comment by jonathanolson** [comment]
@zepumph can you review the above and my commits? I believe I've handled or responded to everything.

**Comment by zepumph** [comment]
Can you please say a sentence about why we were using jsondiffpatch, even though we didn't end up going with that strategy?

>I have a preference for all the exact locales first, then fallbacks (since ar could have translations that might not be understood by someone who knwos ar_MA and es)

Makes a lot of sense.


I like the documentation! Thanks again for all this awesome work. What progress for PhET's codebase! Fee free to close.

**Comment by samreid** [comment]
I don't think the remaining questions are blocking RC's for Gravity and Orbits, so I'll update this on the project board.

**Comment by jonathanolson** [comment]
> Can you please say a sentence about why we were using jsondiffpatch, even though we didn't end up going with that strategy?

In a case where we had a large JSON structure of "original string state" and "string state after", it was useful to diff the entire structure. Later once we had each LocalizedString with its individual knowledge, that wasn't necessary.
